### ISSUE TITLE
Raw NBConvert issues

### ISSUE THREAD

**Issue by mlamoureux** [uclmr/egal#1]
The SVG from egal editor is stored in the cell, but it seems impossible to copy-and-paste that image into another cell. The pasted version appears as raw code, not as an image. 

Similarly, if the user changes the original cell type from "Raw NB Convert" to "Code" or "Markdown", it is impossible to go back to the drawing. Switching back to "Raw NB Convert" just leaves a bunch of raw code displayed. It does not show the image or the editor. 

Ideally, I would like an image that I can copy and paste, or move to other parts of the notebook (or even copy into a new notebook). Or save to the Jupyter hub file system.

**Comment by riedelcastro** [comment]
Completely agree. I might find some time this term to fix this.

**Comment by riedelcastro** [comment]
This should be fixed now in the master and latest release.
